package uk.gov.justice.digital.hmpps.electronicmonitoringdatastoreapi.model.entity

data class AmOrderDetails(
  val legacySubjectId: String,
  val legacyOrderId: String?,
  val firstName: String?,
  val lastName: String?,
  val alias: String?,
  val dateOfBirth: String?,
  val legacyGender: String?,
  val specialInstructions: String?,
  val phoneOrMobileNumber: String?,
  val primaryAddressLine1: String?,
  val primaryAddressLine2: String?,
  val primaryAddressLine3: String?,
  val primaryAddressPostCode: String?,
  val orderStartDate: String?,
  val orderEndDate: String?,
  val enforceableCondition: String?,
  val orderType: String?,
  val orderTypeDescription: String?,
  val orderEndOutcome: String?,
  val responsibleOrgDetailsPhoneNumber: String?,
  val responsibleOrgDetailsEmail: String?,
  val tagAtSource: String?,
)
