hmpps.sqs:
  provider: localstack
  useWebToken: false
  queues:
    audit:
      queueName: "audit"

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?sslmode=prefer
    username: postgres
    password: postgres
  flyway:
    enabled: false

services:
  hmpps-auth:
    url: ${HMPPS_AUTH_URL:http://localhost:8090/auth}

aws:
  region: eu-west-2
  athena:
    role-general: fakeGeneralAccessIAM
    role-restricted: fakeRestrictedAccessIAM

datastore:
  database: historic_api_mart
  output-bucket-arn: s3://emds-test-athena-query-results-20240923095933297100000013
