hmpps.sqs:
  provider: localstack
  useWebToken: false
  queues:
    audit:
      queueName: "audit"

services:
  hmpps-auth:
    url: http://localhost:9090/auth
    # url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  athena:
    database: historic_api_mart
    output: s3://emds-test-athena-query-results-20240923095933297100000013

CLIENT_ID: hmpps-electronic-monitoring-datastore-api
CLIENT_SECRET: clientsecret