package uk.gov.justice.digital.hmpps.electronicmonitoringdatastoreapi.model

import uk.gov.justice.digital.hmpps.electronicmonitoringdatastoreapi.model.athena.AthenaAmOrderDetailsDTO

data class AmOrderDetails(
  override val specials: String,
  override val legacySubjectId: String,
  override val legacyOrderId: String,
  override val firstName: String? = "",
  override val lastName: String? = "",
  override val alias: String? = "",
  override val dateOfBirth: String? = "",
  override val sex: String? = "",
  override val primaryAddressLine1: String? = "",
  override val primaryAddressLine2: String? = "",
  override val primaryAddressLine3: String? = "",
  override val primaryAddressPostCode: String? = "",
  override val phoneOrMobileNumber: String? = "",
  override val orderStartDate: String? = "",
  override val orderEndDate: String? = "",
  override val orderType: String? = "",
  override val orderTypeDescription: String? = "",
  val enforceableCondition: String? = "",
  val orderEndOutcome: String? = "",
  val responsibleOrgDetailsPhoneNumber: String? = "",
  val responsibleOrgDetailsEmail: String? = "",
  val tagAtSource: String? = "",
  val specialInstructions: String? = "",
) : OrderDetailsBase(
  "AM,",
  specials,
  legacySubjectId,
  legacyOrderId,
  firstName,
  lastName,
  alias,
  dateOfBirth,
  sex,
  primaryAddressLine1,
  primaryAddressLine2,
  primaryAddressLine3,
  primaryAddressPostCode,
  phoneOrMobileNumber,
  orderStartDate,
  orderEndDate,
  orderType,
  orderTypeDescription,
) {
  constructor(dto: AthenaAmOrderDetailsDTO) : this (
    specials = "no",
    legacySubjectId = dto.legacySubjectId,
    legacyOrderId = dto.legacyOrderId,
    firstName = dto.firstName,
    lastName = dto.lastName,
    alias = dto.alias,
    dateOfBirth = dto.dateOfBirth,
    sex = dto.sex,
    primaryAddressLine1 = dto.primaryAddressLine1,
    primaryAddressLine2 = dto.primaryAddressLine2,
    primaryAddressLine3 = dto.primaryAddressLine3,
    primaryAddressPostCode = dto.primaryAddressPostCode,
    phoneOrMobileNumber = dto.phoneOrMobileNumber,
    orderStartDate = dto.orderStartDate,
    orderEndDate = dto.orderEndDate,
    orderType = dto.orderType,
    orderTypeDescription = dto.orderTypeDescription,
    enforceableCondition = dto.enforceableCondition,
    orderEndOutcome = dto.orderEndOutcome,
    responsibleOrgDetailsPhoneNumber = dto.responsibleOrgDetailsPhoneNumber,
    responsibleOrgDetailsEmail = dto.responsibleOrgDetailsEmail,
    tagAtSource = dto.tagAtSource,
    specialInstructions = dto.specialInstructions,
  )
}
