package uk.gov.justice.digital.hmpps.electronicmonitoringdatastoreapi.model

import uk.gov.justice.digital.hmpps.electronicmonitoringdatastoreapi.model.athena.AthenaCapOrderDetailsDTO

data class CapOrderDetails(
  override val specials: String,
  override val legacySubjectId: String,
  override val legacyOrderId: String,
  override val firstName: String? = "",
  override val lastName: String? = "",
  override val alias: String? = "",
  override val dateOfBirth: String? = "",
  val adultOrChild: String? = "",
  override val sex: String? = "",
  val contact: String? = "",
  override val primaryAddressLine1: String? = "",
  override val primaryAddressLine2: String? = "",
  override val primaryAddressLine3: String? = "",
  override val primaryAddressPostCode: String? = "",
  override val phoneOrMobileNumber: String? = "",
  val ppo: String? = "",
  val mappa: String? = "",
  val technicalBail: String? = "",
  val manualRisk: String? = "",
  val offenceRisk: Boolean,
  val postCodeRisk: String? = "",
  val falseLimbRisk: String? = "",
  val migratedRisk: String? = "",
  val rangeRisk: String? = "",
  val reportRisk: String? = "",
  override val orderStartDate: String? = "",
  override val orderEndDate: String? = "",
  override val orderType: String? = "",
  override val orderTypeDescription: String? = "",
  val orderTypeDetail: String? = "",
  val wearingWristPid: String? = "",
  val notifyingOrganisationDetailsName: String? = "",
  val responsibleOrganisation: String? = "",
  val responsibleOrganisationDetailsRegion: String? = "",
) : OrderDetailsBase(
  "CAP",
  specials,
  legacySubjectId,
  legacyOrderId,
  firstName,
  lastName,
  alias,
  dateOfBirth,
  sex,
  primaryAddressLine1,
  primaryAddressLine2,
  primaryAddressLine3,
  primaryAddressPostCode,
  phoneOrMobileNumber,
  orderStartDate,
  orderEndDate,
  orderType,
  orderTypeDescription,
) {
  constructor(dto: AthenaCapOrderDetailsDTO) : this (
    specials = "no",
    legacySubjectId = dto.legacySubjectId,
    legacyOrderId = dto.legacyOrderId,
    firstName = dto.firstName,
    lastName = dto.lastName,
    alias = dto.alias,
    dateOfBirth = dto.dateOfBirth,
    adultOrChild = dto.adultOrChild,
    sex = dto.sex,
    contact = dto.contact,
    primaryAddressLine1 = dto.primaryAddressLine1,
    primaryAddressLine2 = dto.primaryAddressLine2,
    primaryAddressLine3 = dto.primaryAddressLine3,
    primaryAddressPostCode = dto.primaryAddressPostCode,
    phoneOrMobileNumber = dto.phoneOrMobileNumber,
    ppo = dto.ppo,
    mappa = dto.mappa,
    technicalBail = dto.technicalBail,
    manualRisk = dto.manualRisk,
    offenceRisk = dto.offenceRisk,
    postCodeRisk = dto.postCodeRisk,
    falseLimbRisk = dto.falseLimbRisk,
    migratedRisk = dto.migratedRisk,
    rangeRisk = dto.rangeRisk,
    reportRisk = dto.reportRisk,
    orderStartDate = dto.orderStartDate,
    orderEndDate = dto.orderEndDate,
    orderType = dto.orderType,
    orderTypeDescription = dto.orderTypeDescription,
    orderTypeDetail = dto.orderTypeDetail,
    wearingWristPid = dto.wearingWristPid,
    notifyingOrganisationDetailsName = dto.notifyingOrganisationDetailsName,
    responsibleOrganisation = dto.responsibleOrganisation,
    responsibleOrganisationDetailsRegion = dto.responsibleOrganisationDetailsRegion,
  )
}
