generic-service:
  nameOverride: hmpps-electronic-monitoring-datastore-api
  productId: "HMPPS529" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-electronic-monitoring-datastore-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    tlsSecretName: hmpps-electronic-monitoring-datastore-cert
    modsecurity_enabled: true
    modsecurity_github_team: "hmpps-electronic-monitoring"

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USEWEBTOKEN: true

  # namespace_secrets:

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  namespace_secrets:
    # [name of kubernetes secret]:
    #   [name of environment variable as seen by app]: [key of kubernetes secret to load]
    #   Environment variables map to application.yml hierarchy levels via underscores
    hmpps-electronic-monitoring-datastore-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      # CLIENT_ID: "API_CLIENT_ID"                              # <== COMMENTED OUT to investigate failing build 20/12/2024
      # CLIENT_SECRET: "API_CLIENT_SECRET"                      # <== COMMENTED OUT to investigate failing build 20/12/2024
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUEARN: "sqs_queue_arn"
      HMPPS_SQS_QUEUES_AUDIT_QUEUENAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-electronic-monitoring-datastore-api
