---
# Per environment values which override defaults in hmpps-electronic-monitoring-datastore-api/values.yaml

generic-service:
  ingress:
    host: electronic-monitoring-datastore-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENV: prod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

  namespace_secrets:
    hmpps-auth:
      CLIENT_ID: "client-id"
      CLIENT_SECRET: "client-secret"
    other-services:
      APPINSIGHTS_INSTRUMENTATIONKEY: "azure-app-insights"
      SENTRY_DSN: "sentry"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
