---
# Per environment values which override defaults in hmpps-electronic-monitoring-datastore-api/values.yaml

generic-service:
  serviceAccountName: "hmpps-em-datastore-prod-athena"

  ingress:
    hosts:
      - electronic-monitoring-datastore-api.hmpps.service.justice.gov.uk

  env:
#    SENTRY_ENV: prod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    ATHENA_DATABASE_NAME: "historic_api_mart"
#    ATHENA_OUTPUT_BUCKET: "s3://emds-prod-athena-query-results-20240918073115959600000002"
    ATHENA_OUTPUT_BUCKET: "s3://emds-test-athena-query-results-20240923095933297100000013"

    # ROLES NOTE: Currently the specials role is set to the same non-specials IAM role as the general role. This will change once we pull specials through.
    ATHENA_SPECIALS_IAM_ROLE: "arn:aws:iam::396913731313:role/cmt_read_emds_data_test"
    ATHENA_GENERAL_IAM_ROLE: "arn:aws:iam::396913731313:role/cmt_read_emds_data_test"
    MFA_REQUIRED: "false"

#  namespace_secrets:
#    hmpps-auth:
#      CLIENT_ID: "client-id"
#      CLIENT_SECRET: "client-secret"
#    other-services:
#      APPINSIGHTS_INSTRUMENTATIONKEY: "azure-app-insights"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
