---
# Per environment values which override defaults in hmpps-electronic-monitoring-datastore-api/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: "hmpps-em-datastore-dev-athena"

  ingress:
    host: electronic-monitoring-datastore-api-dev.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: dev
    SENTRY_ENV: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

  namespace_secrets:
    hmpps-auth:
      CLIENT_ID: "client-id"
      CLIENT_SECRET: "client-secret"
    other-services:
      APPINSIGHTS_INSTRUMENTATIONKEY: "azure-app-insights"
      SENTRY_DSN: "sentry"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
